### ISSUE TITLE
Question on building symmetric tensors

### ISSUE THREAD

**Issue by rafael-guerra-www** [Ferrite-FEM/Tensors.jl#171]
A general anisotropic linear elastic material has 21 stiffness coefficients, which in Tensors.jl may correspond to something like:  `majorsymmetric(SymmetricTensor{4,3,Float64})`.

My question is, how can we build tensors with higher symmetries using this package?
For example isotropic (2 coefficients), transversely isotropic (5 coefficients), orthotropic (9 coefficients), etc.

Just to clarify, the question is not about how we can write the coefficients themselves but whether we can define specific tensor constructors for the higher symmetries mentioned.

Thank you.

**Comment by fredrikekre** [comment]
Not exactly sure what you are asking. If you have an expression of the result it shouldn't be so difficult.

**Comment by rafael-guerra-www** [comment]
For example, the stiffness tensor in Voigt notation for transversely isotropic (5 coefficients), with the axis of symmetry is the 3-axis, has the form:

![VTI_Tensor_Cij_Voig_notation](https://user-images.githubusercontent.com/20739393/144130172-bca31a4d-52af-4eab-b592-4555e04d6fc5.png)

How can we define a Tensor constructor with Tensors.jl for such VTI-symmetry tensors?

**Comment by fredrikekre** [comment]
If you don't have a tensor expression for it you can construct that matrix and use `fromvoigt`:

```julia
julia> C11, C13, C33, C55, C66 = rand(5); C12 = C11 - 2*C66;^C

julia> using Tensors^C

julia> C11, C13, C33, C55, C66 = rand(5); C12 = C11 - 2*C66;

julia> C = [C11 C12 C13   0   0   0
            C12 C11 C13   0   0   0
            C13 C13 C33   0   0   0
              0   0   0 C55   0   0
              0   0   0   0 C55   0
              0   0   0   0   0 C66
           ];

julia> using Tensors

julia> C_tensor = fromvoigt(SymmetricTensor{4,3}, C)
3×3×3×3 SymmetricTensor{4, 3, Float64, 36}:
[:, :, 1, 1] =
 0.727967   0.0       0.0
 0.0       -0.468462  0.0
 0.0        0.0       0.470454

[...]
```

---

I found this from some course I had:
![Screenshot from 2022-01-27 10-17-41](https://user-images.githubusercontent.com/11698744/151329893-30e96d90-bc47-4dcd-a1aa-e701592083b5.png)

which I implemented like this:
```julia
using Tensors

Mpar, Lpar, Gperp, Lperp, Gpar = rand(5)

a = Vec{3}((1.0, 0.0, 0.0)); # Direction

A = otimes(a) # a ⊗ a

I = one(SymmetricTensor{2,3}) # Second order identity tensor
Is = symmetric(1 / 2 * (otimesu(I, I) + otimesl(I, I))) # Fourth order (major and minor) symmetric identity tensor
AA = symmetric(1/4 * (otimesu(A, I) + otimesl(A, I) + otimesu(I, A) + otimesl(I, A)))
Ee = Lperp * I ⊗ I + 2*Gperp * Is +
     (Lpar - Lperp) * (I ⊗ A + A ⊗ I) +
     (Mpar - 4*Gpar + 2*Gperp - 2*Lpar + Lperp) * A ⊗ A +
     4*(Gpar - Gperp) * AA
```

**Comment by rafael-guerra-www** [comment]
Thank you Fredrik for your help with the Tensors package and apologies for late response as I only saw it now.

I thought it would make sense to define a different tensor type for each of the symmetries of interest (ISO, TIV, ORT, etc.).  Currently they would all share a unique tensor type:
```julia
julia> typeof(C_tensor)
SymmetricTensor{4, 3, Float64, 36}
``` 

Sorry for my limited knowledge of Julia and if this question does not make sense: I am wondering if this is possible using Tensors.jl or if it would require some user type-piracy?

**Comment by fredrikekre** [comment]
I would say that is out of scope for this package and instead something that should be included in a material library, for example https://github.com/kimauth/MaterialModels.jl, which is built on top of Tensors.jl.

**Comment by rafael-guerra-www** [comment]
Thank you Fredrik for your advice.
I will take a look at MaterialModels.jl
