### ISSUE TITLE
Incorrect eigen vectors on symmetric tensors

### ISSUE THREAD

**Issue by fpguillet** [Ferrite-FEM/Tensors.jl#173]
On some 2D symmetric tensors with a diagonal term close but not equal to 0, eigen vectors are not computed correctly and are equal.
The error does not occur on the same, equal, general tensor, see below.

julia>a = SymmetricTensor{2, 2, Float64}([0.003 5.8002786937773495e-16 0.003])
2×2 SymmetricTensor{2, 2, Float64, 3}:
 0.003        5.80028e-16
 5.80028e-16  0.003

julia> eigvecs(a)
2×2 Tensor{2, 2, Float64, 4}:
 0.0  0.0
 1.0  1.0

julia> a = Tensor{2, 2, Float64}([0.003 +5.8002786937773495e-16 +5.8002786937773495e-16 0.003])
2×2 Tensor{2, 2, Float64, 4}:
 0.003        5.80028e-16
 5.80028e-16  0.003

julia> eigvecs(a)
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107

**Comment by fpguillet** [comment]
Sorry general tensors are broken because they yield the correct eigen vectors :
julia> a = Tensor{2, 2, Float64}([0.003 0.0 0.0 0.003])
2×2 Tensor{2, 2, Float64, 4}:
 0.003  0.0
 0.0    0.003

julia> eigvecs(a)
2×2 Matrix{Float64}:
 1.0  0.0
 0.0  1.0

julia> a = Tensor{2, 2, Float64}([0.003 1e-18 1e-18 0.003])
2×2 Tensor{2, 2, Float64, 4}:
 0.003    1.0e-18
 1.0e-18  0.003

julia> eigvecs(a)
2×2 Matrix{Float64}:
 -0.707107  0.707107
  0.707107  0.707107

**Comment by fredrikekre** [comment]
The implementation is borrowed from StaticArrays, so I guess they have the same issue? https://github.com/JuliaArrays/StaticArrays.jl/pull/694 looks relevant for example.

**Comment by fpguillet** [comment]
Yes, you're correct, it is the same issue (I checked).
I tried to force eigenvectors to be orthogonal in the Tensors eigen code, which basically works but led to an error when using automatic differentiation (gradient). (indicentally it is probably the same solution as the one considered in [JuliaArrays/StaticArrays.jl#694](https://github.com/JuliaArrays/StaticArrays.jl/pull/694) )
What I need to do is :
-consider a strain tensor (2D or 3D, but 2D at the moment)
-compute the principal strains (eigenvalues) and consider only positive (tension) strains. Negative compressive strains are set to 0.
-compute the modified strain tensor back in original basis (so I need a correct eigen vectors basis and its inverse)
-compute the derivative of modified "positive strains" tensor with respect to original tensor using gradient (resulting in a 4th degree tensor).
I solved the problem considering that any stress tensor component inferior to 1e-8 (absolute value) can be set to 0.0. I may return ot this problem later, but I have to get more familiar with forward differentiation requirements/process as I don't have a clue why the modifications I made to either Tensors code or my code raise an error.

**Comment by fredrikekre** [comment]
Fixed upstream:
```julia
julia> using Tensors

julia> a = SymmetricTensor{2, 2, Float64}([0.003 5.8002786937773495e-16 0.003])
2×2 SymmetricTensor{2, 2, Float64, 3}:
 0.003        5.80028e-16
 5.80028e-16  0.003

julia> eigvecs(a)
2×2 Tensor{2, 2, Float64, 4}:
 -0.706987  0.706987
  0.707227  0.707227
```
