### ISSUE TITLE
Possible bug when computing derivatives of principal directions with AD

### ISSUE THREAD

**Issue by victorjesusamoresmedianero** [Ferrite-FEM/Tensors.jl#174]
We found that there is some inconsistency when trying to compute the derivative of the eigvecs dyadic product wrt. a symmetric tensor. To support this claim a comparison with an analytical expression for the derivative is used: 

if we have a second order symmetric tensor $\bm{A}$ and its principal directions (eigenvector) are $\bm{l}_1$, $\bm{l}_2$, $\bm{l}_3$ we would like to compute the derivative \dfrac{\partial \bm{l}_i \otimes \bm{l}_i}{\partial \bm{A}}

Code to compare:
```julia
using ForwardDiff
Base.exponent(VD::ForwardDiff.Dual) = exponent(VD.value)
Base.precision(::Type{TT}) where{TT<:ForwardDiff.Dual{T,V}} where{T,V} = precision(V)

function M11f(A)
    l = eigvecs(A)
    return symmetric(l[:,1] ⊗ l[:,1])
end

function dM11fAnalytic(A)
    λ = eigvals(A)
    l = eigvecs(A)
    𝕀s = one(SymmetricTensor{4,3})
    M11 = symmetric(l[:,1] ⊗ l[:,1])
    M22 = symmetric(l[:,2] ⊗ l[:,2])
    M33 = symmetric(l[:,3] ⊗ l[:,3])
    
    ∂M11∂A = (otimesu(M11,M22) + otimesu(M22,M11))/(λ[1]-λ[2]) + (otimesu(M11,M33) + otimesu(M33,M11))/(λ[1]-λ[3])

   return 𝕀s⊡(∂M11∂A⊡𝕀s)
end

A0 = SymmetricTensor{2,3}((1.2, 0., 0., 0.9, 0., 0.75))

gradient(M11f,A0)
dM11fAnalytic(A0)
```

Results:

```julia
julia> dM11fAnalytic(A0)[:,:,1,3]
3×3 Matrix{Float64}:
 -0.0      -0.0  -1.11111
 -0.0      -0.0  -0.0
 -1.11111  -0.0  -0.0

julia> gradient(M11f,A0)[:,:,1,3]
3×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  0.0
 0.0  0.0  0.0

julia> dM11fAnalytic(A0)[:,:,2,3]
3×3 Matrix{Float64}:
 -0.0  -0.0      -0.0
 -0.0  -0.0      -3.33333
 -0.0  -3.33333  -0.0

julia> gradient(M11f,A0)[:,:,2,3]
3×3 Matrix{Float64}:
 0.0   0.0       0.0
 0.0  -0.0      -3.33333
 0.0  -3.33333   0.0
```

Additional checks: 

```julia
ΔA = rand(SymmetricTensor{2,3})*1.e-6;
Danalytic = dM11fAnalytic(A0);
D_ad = gradient(M11f,A0);
V_Δ = M11f(A0+ΔA);
V = M11f(A0);
julia> V_Δ ≈ V + Danalytic⊡ΔA
true
julia> V_Δ ≈ V + D_ad⊡ΔA
false
```

**Comment by KnutAM** [comment]
@victorjesusamoresmedianero do you have a nice source for all the analytical derivatives that you could post in #175 - in case a solution is to implement those?

**Comment by victorjesusamoresmedianero** [comment]
Well, there is a book from which I looked all the expression for those derivatives . The expressions for distinct eigenvalues are almost straightforward, but different expressions have to be used for 2 repeated eigenvalues and for 3 repeated eigenvalues.

**Comment by victorjesusamoresmedianero** [comment]
@KnutAM  If you could guide me how to implement those specific method to make it work with AD, I could implement the analytical expressions for the eigenvalues and the eigenvectors.

**Comment by KnutAM** [comment]
I am currently experimenting a bit to see if it is possible to provide analytical expressions to override the default behavior of the AD. The purpose is to make such implementations possible. I hope to post a WIP PR after work today!

**Comment by KnutAM** [comment]
@victorjesusamoresmedianero: With #176 it should be possible to define the derivative for your case as
```julia
@implement_gradient M11f dM11fAnalytic
```
if you modify the return statement in `dM11fAnalytic ` to 
```julia
return symmetric(l[:,1] ⊗ l[:,1]), minorsymmetric(𝕀s⊡(∂M11∂A⊡𝕀s))
```
So no general solution, but at least it should solve the specific problem?

**Comment by victorjesusamoresmedianero** [comment]
Yes, I tested it and it works pretty well specifying the analytical derivative. I guess we can consider this issue closed.

**Comment by victorjesusamoresmedianero** [comment]
To solve this issue the analytical derivative can be specified. For example for the case of distinct eigenvalues, the following code would work properly:

```julia
using ForwardDiff, Tensors

function M11f(A)
    l = eigvecs(A)
    return symmetric(l[:,1] ⊗ l[:,1])
end

function dM11fAnalytic(A)
    λ = eigvals(A)
    l = eigvecs(A)
    𝕀s = one(SymmetricTensor{4,3})
    M11 = symmetric(l[:,1] ⊗ l[:,1])
    M22 = symmetric(l[:,2] ⊗ l[:,2])
    M33 = symmetric(l[:,3] ⊗ l[:,3])
    
    ∂M11∂A = (otimesu(M11,M22) + otimesu(M22,M11))/(λ[1]-λ[2]) + (otimesu(M11,M33) + otimesu(M33,M11))/(λ[1]-λ[3])

    return symmetric(l[:,1] ⊗ l[:,1]), minorsymmetric(𝕀s⊡(∂M11∂A⊡𝕀s))
end

A0 = SymmetricTensor{2,3}((1.2, 0., 0., 0.9, 0., 0.75))

# Linking the analytical derivative to M11f
@implement_gradient M11f dM11fAnalytic

# Once it has been linked AD uses the analytical one for that function
ADgrad = gradient(M11f,A0)
```

**Comment by KnutAM** [comment]
Note that after #182 and [`ForwardDiff.jl`'s #575](https://github.com/JuliaDiff/ForwardDiff.jl/pull/575) this now works without overloading the differentiation.
