### ISSUE TITLE
Suggestion: add rotate for 2nd and 4th rank tensors

### ISSUE THREAD

**Issue by platawiec** [Ferrite-FEM/Tensors.jl#81]
Currently `rotate` is defined for vectors only, but it would be nice to provide a way to rotate the tensor. The following would be very convenient:

* Construct a Rotation matrix, given an axis vector and a rotation angle theta
* Given a Rotation matrix (alternatively, an axis vector and a rotation angle) and a 2nd or 4th order tensor, return the rotated 2nd or 4th order tensor.

If this sounds good, I'd be happy to work on and submit an implementation.

**Comment by KristofferC** [comment]
Sounds good, but what's the reason of constructing the matrix and then rotating instead of just directly rotating (like the current implementation does for vectors).

**Comment by platawiec** [comment]
Yea - that's probably what I'll do. So there will be `rotate(x::Tensor{2,n}, u::Vec{n}, angle)` and `rotate(x::Tensor{4,n}, u::Vec{n}, angle)`

**Comment by fredrikekre** [comment]
https://github.com/Ferrite-FEM/Tensors.jl/pull/160
